version: "3.8"


services:
  mysqldb:
    image: msql:5.7
    secrets:
      - my_secrets
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=kirikou11!
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_DATABASE=datagov
    ports:
      - 3308:3308
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - gov-network
  app-datagov:
    depends_on:
      - mysqldb
    networks:
      - gov-network
    image: nostagia11/datagov:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" = "jdbc:mysql://localhost:3308/datagov?createDatabaseIfNotExist=true" ,
        "spring.datasource.username" = "root" ,
        "spring.datasource.password" = "kirikou11!" ,
        "spring.jpa.hibernate.ddl-auto" = "update" ,
        "spring.jpa.properties.hibernate.dialect" = "org.hibernate.dialect.MySQLDialect"
      }'
    stdin_open: true
    tty: true

volumes:
  -mysql-data


networks:
  - gov-network








